version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - Jpfonseca
  assignees:
  - Jpfonseca
  labels:
  - enhancement
  versioning-strategy: increase
